site_name: CS 自学笔记
site_url: https://SuruiLiu.github.io
repo_url: https://github.com/SuruiLiu/cs-notes
repo_name: SuruiLiu/cs-notes

theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  features:
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SuruiLiu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/suruiliu/
  generator: false  # 移除 "Made with Material for MkDocs"
  copyright: Copyright &copy; 2024 <a href="https://github.com/SuruiLiu" target="_blank">Surui Liu</a>

# 添加页脚配置
copyright: >
  Copyright &copy; 2025
  <a href="https://github.com/SuruiLiu" target="_blank">Surui Liu</a> 

analytics:
  provider: google
  property: !ENV GOOGLE_ANALYTICS_KEY

markdown_extensions:
  - tables
  - attr_list
  - def_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search:
      lang: zh
  - tags
  - git-revision-date-localized:
      type: datetime
      locale: zh
      timezone: Asia/Shanghai
      enable_creation_date: true
  - minify:
      minify_html: true

nav:
  - 前言: index.md
  - Web开发:
    - 概述: web-dev/index.md
    - 前端: web-dev/frontend/index.md
    - 后端: web-dev/backend/index.md
    - 数据库: web-dev/database/index.md
    - 服务器: web-dev/server/index.md
    - 安全: web-dev/security/index.md
  - 系统架构: 
    - 深入理解计算机系统: infra/csapp/overview.md
    - 计算机网络: infra/network.md
    - 操作系统: infra/os.md
    - 并行与分布式系统: infra/distributed/index.md
    - 计算机系统安全: infra/security/index.md
  - Web3:
    - 区块链: web3/blockchain/index.md
    - 智能合约: web3/contracts/index.md
    - 去中心化应用: web3/dapps/index.md
    - 安全审计: web3/security/index.md