site_name: CS 自学笔记
site_url: https://SuruiLiu.github.io
repo_url: https://github.com/SuruiLiu/cs-notes
repo_name: SuruiLiu/cs-notes

theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
    
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SuruiLiu
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

markdown_extensions:
  - tables
  - attr_list
  - def_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search:
      lang: zh
  - tags
  - git-revision-date-localized:
      type: datetime
      locale: zh
      timezone: Asia/Shanghai
      enable_creation_date: true
  - minify:
      minify_html: true

nav:
  - 首页: index.md
  - Web开发:
    - web-dev/index.md
  - Web3:
    - web3/index.md
  - 基础设施:
    - infra/index.md 